server:
  host: "0.0.0.0"
  port: 50051
  version: "2.0.0"


logging:
  level: "INFO"
  file: "inference_server.log"

metrics:
  enabled: true
  port: 8000


model:
  path: "yolov10x.pt"
  confidence_threshold: 0.01
  nms_threshold: 0.85  # default 0.7
  classNames: {
    "0": "person",
    "13": "bench",
    "24": "backpack",
    "25": "umbrella",
    "26": "handbag",
    "28": "suitcase",
    "39": "bottle",
    "41": "cup",
    "56": "chair",
    "57": "couch",
    "60": "dining table",
    "63": "laptop",
    "64": "mouse",
    "66": "keyboard",
    "67": "cell phone",
    "73": "book",
  }