services:
  my-python-app:
    build: .
    container_name: inference_custom
    runtime: nvidia
    volumes:
      - ./app:/app
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8000:8000"
      - "8001:8001"
      - "50051:50051"
