# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\"\"\n\x11PredictionRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"$\n\x12PredictionResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2H\n\x10InferenceService\x12\x34\n\x07Predict\x12\x12.PredictionRequest\x1a\x13.PredictionResponse\"\x00\x62\x06proto3')



_PREDICTIONREQUEST = DESCRIPTOR.message_types_by_name['PredictionRequest']
_PREDICTIONRESPONSE = DESCRIPTOR.message_types_by_name['PredictionResponse']
PredictionRequest = _reflection.GeneratedProtocolMessageType('PredictionRequest', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTIONREQUEST,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:PredictionRequest)
  })
_sym_db.RegisterMessage(PredictionRequest)

PredictionResponse = _reflection.GeneratedProtocolMessageType('PredictionResponse', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTIONRESPONSE,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:PredictionResponse)
  })
_sym_db.RegisterMessage(PredictionResponse)

_INFERENCESERVICE = DESCRIPTOR.services_by_name['InferenceService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PREDICTIONREQUEST._serialized_start=19
  _PREDICTIONREQUEST._serialized_end=53
  _PREDICTIONRESPONSE._serialized_start=55
  _PREDICTIONRESPONSE._serialized_end=91
  _INFERENCESERVICE._serialized_start=93
  _INFERENCESERVICE._serialized_end=165
# @@protoc_insertion_point(module_scope)
