# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\"\"\n\x11PredictionRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"$\n\x12PredictionResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2H\n\x10InferenceService\x12\x34\n\x07Predict\x12\x12.PredictionRequest\x1a\x13.PredictionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTIONREQUEST']._serialized_start=19
  _globals['_PREDICTIONREQUEST']._serialized_end=53
  _globals['_PREDICTIONRESPONSE']._serialized_start=55
  _globals['_PREDICTIONRESPONSE']._serialized_end=91
  _globals['_INFERENCESERVICE']._serialized_start=93
  _globals['_INFERENCESERVICE']._serialized_end=165
# @@protoc_insertion_point(module_scope)
