# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"$\n\x0ePredictRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\";\n\x0fPredictResponse\x12(\n\ndetections\x18\x01 \x03(\x0b\x32\x14.inference.Detection\")\n\x13\x42\x61tchPredictRequest\x12\x12\n\nimage_data\x18\x01 \x03(\x0c\"C\n\x14\x42\x61tchPredictResponse\x12+\n\x07results\x18\x01 \x03(\x0b\x32\x1a.inference.PredictResponse\"(\n\x12TestPredictRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"\xf0\x01\n\x13TestPredictResponse\x12(\n\ndetections\x18\x01 \x03(\x0b\x32\x14.inference.Detection\x12\x12\n\norig_shape\x18\x02 \x01(\t\x12\r\n\x05\x62oxes\x18\x03 \x01(\t\x12\r\n\x05probs\x18\x04 \x01(\t\x12\x11\n\tkeypoints\x18\x05 \x01(\t\x12\x0b\n\x03obb\x18\x06 \x01(\t\x12\r\n\x05speed\x18\x07 \x01(\t\x12\r\n\x05names\x18\x08 \x01(\t\x12\x13\n\x0bjson_output\x18\t \x01(\t\x12\x12\n\nplot_image\x18\n \x01(\x0c\x12\x16\n\x0everbose_output\x18\x0b \x01(\t\"<\n\tDetection\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x0c\n\x04\x62\x62ox\x18\x03 \x03(\x02\x32\xf9\x01\n\x10InferenceService\x12\x42\n\x07Predict\x12\x19.inference.PredictRequest\x1a\x1a.inference.PredictResponse\"\x00\x12Q\n\x0c\x42\x61tchPredict\x12\x1e.inference.BatchPredictRequest\x1a\x1f.inference.BatchPredictResponse\"\x00\x12N\n\x0bTestPredict\x12\x1d.inference.TestPredictRequest\x1a\x1e.inference.TestPredictResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=30
  _globals['_PREDICTREQUEST']._serialized_end=66
  _globals['_PREDICTRESPONSE']._serialized_start=68
  _globals['_PREDICTRESPONSE']._serialized_end=127
  _globals['_BATCHPREDICTREQUEST']._serialized_start=129
  _globals['_BATCHPREDICTREQUEST']._serialized_end=170
  _globals['_BATCHPREDICTRESPONSE']._serialized_start=172
  _globals['_BATCHPREDICTRESPONSE']._serialized_end=239
  _globals['_TESTPREDICTREQUEST']._serialized_start=241
  _globals['_TESTPREDICTREQUEST']._serialized_end=281
  _globals['_TESTPREDICTRESPONSE']._serialized_start=284
  _globals['_TESTPREDICTRESPONSE']._serialized_end=524
  _globals['_DETECTION']._serialized_start=526
  _globals['_DETECTION']._serialized_end=586
  _globals['_INFERENCESERVICE']._serialized_start=589
  _globals['_INFERENCESERVICE']._serialized_end=838
# @@protoc_insertion_point(module_scope)
